config/routes.rb
Rails.application.routes.draw do
  root 'page#index'

  resources :matches
  devise_for :users, :controllers => { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords' }

end

app/models/match.rb
class Match < ActiveRecord::Base
	belongs_to :player_home, :class_name => "User", :foreign_key => "player_home_id"
	belongs_to :player_visit, :class_name => "User", :foreign_key => "player_visit_id"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :matches

  def fullname
  	self.first_name + " " + self.last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new

    @users = User.all
  end

  # GET /matches/1/edit
  def edit
    @users = User.all
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:player_home_id, :player_visit_id, :winner, :game1, :game2, :game3, :game4, :game5)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController

  def index
  	@matches = Match.all
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < Devise::PasswordsController
	layout false
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	
	layout false
	
	private

  	def sign_up_params
    	params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  	end

  	def account_update_params
    	params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
	layout false
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" /> 
  <title>TennisFederation</title>

  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' %> 
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <section class="vbox">
    <header class="bg-dark dk header navbar navbar-fixed-top-xs">
      <div class="navbar-header aside-md" id="brand-tennis-federation">
        <a class="btn btn-link visible-xs" data-toggle="class:nav-off-screen,open" data-target="#nav,html">
          <i class="fa fa-bars"></i>
        </a>
        <a href="#" class="navbar-brand" data-toggle="fullscreen">
          <%= image_tag("http://flatfull.com/themes/note/images/logo.png", class: "m-r-sm") %>Federación de Tenis</a>
        <a class="btn btn-link visible-xs" data-toggle="dropdown" data-target=".nav-user">
          <i class="fa fa-cog"></i>
        </a>
      </div>    
      <ul class="nav navbar-nav navbar-right m-n hidden-xs nav-user">
        <li class="dropdown">
          <% if user_signed_in? %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="thumb-sm avatar pull-left">
                <%= image_tag("http://flatfull.com/themes/note/images/avatar.jpg") %>
              </span> <%= current_user.fullname %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu animated fadeInRight">
              <span class="arrow top"></span>
              <li>
                <%= link_to 'Editar Perfil', edit_user_registration_path %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          <% else %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Ingresar al Sitio 
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu animated fadeInRight">
              <span class="arrow top"></span>
              <li>
                <%= link_to 'Registrarse', new_user_registration_path %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to "Iniciar Sesión", new_user_session_path %>
              </li>
            </ul>
          <% end %>
        </li>
      </ul>      
    </header>
    <section>
      <section class="hbox stretch">
        <section id="content">
          <%= yield %>
        </section>
      </section>
    </section>
  </section>
</body>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Include JQuery -->
  <%= javascript_include_tag 'http://code.jquery.com/jquery-2.2.2.min.js' %>
  <!-- Include bootstrap js -->
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js' %>

</html>

app/views/matches/_form.html.erb
<%= form_for @match do |f| %>
  <div class="form-group">
    <%= f.label :player_home_id, :class => 'control-label' %>
    <%= f.number_field :player_home_id, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :player_visit_id, :class => 'control-label' %>
    <%= f.number_field :player_visit_id, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :winner, :class => 'control-label' %>
    <%= f.number_field :winner, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :result_id, :class => 'control-label' %>
    <%= f.number_field :result_id, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :game1, :class => 'control-label' %>
    <%= f.text_field :game1, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :game2, :class => 'control-label' %>
    <%= f.text_field :game2, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :game3, :class => 'control-label' %>
    <%= f.text_field :game3, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :game4, :class => 'control-label' %>
    <%= f.text_field :game4, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :game5, :class => 'control-label' %>
    <%= f.text_field :game5, :class => 'form-control' %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                matches_path, :class => 'btn' %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<%- model_class = Match -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/matches/index.html.erb
<%- model_class = Match -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:player_home_id) %></th>
      <th><%= model_class.human_attribute_name(:player_visit_id) %></th>
      <th><%= model_class.human_attribute_name(:game1) %></th>
      <th><%= model_class.human_attribute_name(:game2) %></th>
      <th><%= model_class.human_attribute_name(:game3) %></th>
      <th><%= model_class.human_attribute_name(:game4) %></th>
      <th><%= model_class.human_attribute_name(:game5) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= link_to match.id, match_path(match) %></td>
        <% if match.winner == 1 %>
          <td><strong><%= match.player_home.fullname %></strong></td>
        <% else %>
          <td><%= match.player_home.fullname %></td>
        <% end %>
        
        <% if match.winner == 2 %>
          <td><strong><%= match.player_visit.fullname %></strong></td>
        <% else %>
          <td><%= match.player_visit.fullname %></td>
        <% end %>
        <td><%= match.game1 %></td>
        <td><%= match.game2 %></td>
        <td><%= match.game3 %></td>
        <td><%= match.game4 %></td>
        <td><%= match.game5 %></td>
        <td><%=l match.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_match_path(match), :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      match_path(match),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_match_path,
            :class => 'btn btn-primary' %>

app/views/matches/new.html.erb
<%- model_class = Match -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/matches/show.html.erb
<%- model_class = Match -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:player_home_id) %>:</strong></dt>
  <dd><%= @match.player_home_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:player_visit_id) %>:</strong></dt>
  <dd><%= @match.player_visit_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:winner) %>:</strong></dt>
  <dd><%= @match.winner %></dd>
  <dt><strong><%= model_class.human_attribute_name(:result_id) %>:</strong></dt>
  <dd><%= @match.result_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:game1) %>:</strong></dt>
  <dd><%= @match.game1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:game2) %>:</strong></dt>
  <dd><%= @match.game2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:game3) %>:</strong></dt>
  <dd><%= @match.game3 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:game4) %>:</strong></dt>
  <dd><%= @match.game4 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:game5) %>:</strong></dt>
  <dd><%= @match.game5 %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              matches_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_match_path(@match), :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              match_path(@match),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/page/index.html.erb
<ul class="nav nav-tabs">
	<li class="active">
		<a data-toggle="tab" href="#matches">Partidos</a>
	</li>
	<li>
		<a data-toggle="tab" href="#ranking">Ranking</a>
	</li>
</ul>

<div class="tab-content">
	<div id="matches" class="tab-pane fade in active">
		<div class="content">
			<button type="button" class="btn btn-default pull-right">
				<%= link_to "Create Match", new_match_path  %>
			</button>

			<table class="table table-hover">
				<thead>
					<th>Date and Time</th>
					<th>Player home</th>
			  		<th>Player visit</th>
					<th>Game 1</th>
					<th>Game 2</th>
					<th>Game 3</th>
					<th>Game 4</th>
					<th>Game 5</th>
				</thead>
				<tbody>
					<% @matches.each do |match| %>
						<tr>
							<td><%= match.created_at.strftime("%Y %m %d") %>
							<% if match.winner == 1 %>
								<td><strong><%= match.player_home.fullname %></strong></td>
							<% else %>
								<td><%= match.player_home.fullname %></td>
							<% end %>

							<% if match.winner == 2 %>
								<td><strong><%= match.player_visit.fullname %></strong></td>
							<% else %>
								<td><%= match.player_visit.fullname %></td>
							<% end %>
					        <td><%= match.game1 %></td>
					        <td><%= match.game2 %></td>
					        <td><%= match.game3 %></td>
					        <td><%= match.game4 %></td>
					        <td><%= match.game5 %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
	<div id="ranking" class="tab-pane fade">
		<p>Aqui va lo de Rankings!</p>
	</div>
</div>